# Example using MS Build of OpenJDK image directly
FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu

# Continue with your application deployment
RUN mkdir /opt/app

# Copy the application
COPY src/Java/Web/target/*.jar /opt/app/app.jar

CMD [ "java", "-jar", "/opt/app/app.jar" ]